
---
- hosts: localhost
  gather_facts: false
  connection: local
  name: Git add, commit and push updated engagement data
  tasks:
    - name: Git add
      shell: git add .
      args:
        chdir: "{{ directory }}"
    
    - name: Configure Git username and email
      shell: |
        git config --global user.email bot@bot.com;
        git config --global user.name bot

    - name: Git commit
      shell: |
        git commit -m 'Created by Ansible Tower bot'
      args:
        chdir: "{{ directory }}"
      register: git_commit
      changed_when:
        - git_commit.rc == 0
      failed_when:
        - git_commit.rc > 1

    - name: Git push
      shell: git push origin master
      args:
        chdir: "{{ directory }}"
      when:
        git_commit.rc == 0

