---
- name: Test Git Checkout
  hosts: all

  tasks:
    - name: Set fact
      set_fact:
        url: "{{ tower_webhook_payload.project.git_ssh_url }}"
        directory: "{{ playbook_dir }}/{{ tower_webhook_payload.project.id }}"

    - name: Create gitlab project directory
      file:
        path: "{{ directory }}"
        state: directory
        mode: '0775'

    - name: Stat directory
      stat:
        path: "{{ directory }}"

    - name: Git clone
      shell: |
         GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no -i {{ gitlab_ssh_private_key_file }}' git clone {{ url }} {{ directory }}

    - name: Set engagement_data var
      set_fact:
        engagement_data: "{{ lookup('file', (directory + '/iac/engagement.json') | from_json }}"

    - name: Print engagement data
      debug:
        var: engagement_data
        
