---
- name: Test Git Checkout
  hosts: all
 
  tasks:
    - name: Set fact
      set_fact:
        url: "{{ tower_webhook_payload.project.git_ssh_url }}"
        directory: "{{ tower_webhook_payload.project.id }}"

    - name: Create path for Git checkout
      file:
        path: "{{ directory }}"
        state: directory

    - name: Git checkout
      git:
        repo: "{{ url }}"
        dest: "{{ directory }}"
        accept_hostkey: true
        key_file: "{{ gitlab_ssh_private_key_file }}"


    - name: Set engagement_data var
      set_fact:
        engagement_data: "{{ lookup('file', (directory + 'engagement.json')|join('/')) | from_json }}"

    - name: Print engagement data
      debug:
        var: engagement_data
        
