---
- name: Test Git Checkout
  hosts: all

  tasks:
    - name: Set fact
      set_fact:
        url: "{{ tower_webhook_payload.project.git_ssh_url }}"
        directory: "/tmp/git_projects/{{ tower_webhook_payload.project.id }}"

    - name: Create gitlab project directory
      file:
        path: "{{ directory }}"
        state: directory
        mode: '0775'
        recurse: yes

    - name: Git clone engagement repository
      git:
        repo: "{{ url }}"
        dest: "{{ directory }}"
        ssh_opts: "-o StrictHostKeyChecking=no"
        force: true
        key_file: /var/lib/awx/.ssh/bridge-private-key

    - name: Set engagement_data var
      set_fact:
        engagement_data: "{{ lookup('file', directory + '/engagement.json') | from_json }}"
        cacheable: true

    - name: File creation test
      file:
        path: "{{ directory }}/create_file_test.txt"
        state: touch
        mode: '0664'

    - name: Git add
      shell: git add .
      args:
        chdir: "{{ directory }}"

    - name: Git add
      shell: |
        git config --global user.email bot@bot.com;
        git config --global user.name bot;
        git commit -m 'Created by Ansible Tower bot'
      args:
        chdir: "{{ directory }}"

    - name: Git push
      shell: "GIT_SSH_COMMAND='ssh -i /var/lib/awx/.ssh/bridge-private-key -o StrictHostKeyChecking=no' git push origin master"
      args:
        chdir: "{{ directory }}"
