---
- name: Test Git Checkout
  hosts: all
 
  tasks:
    set_fact:
      url: "{{ project.git_ssh_url }}"
      directory: "{{ project.id }}"
    git:
      repo: "{{ url }}"
      dest: "{{ directory }}"
      key_file: "{{ gitlab_ssh_private_key_file }}"