---
- name: Test Git Checkout
  hosts: all
 
  tasks:
    - name: Set fact
      set_fact:
        url: "{{ tower_webhook_payload.project.git_ssh_url }}"
        directory: "{{ tower_webhook_payload.project.id }}"

    - name: Git checkout
      git:
        repo: "{{ url }}"
        dest: "{{ directory }}"
        key_file: "{{ gitlab_ssh_private_key_file }}"