---
- name: Test Git Checkout
  hosts: all
 
  tasks:
    - name: Set fact
      set_fact:
        url: "{{ tower_webhook_payload.project.git_ssh_url }}"
        directory: "{{ tower_webhook_payload.project.id }}"

    - name: Set permissions on SSH key from custom credential
      file:
        path: "{{ gitlab_ssh_private_key_file }}"
        mode: '0600'

    - name: Create git directory
      file:
        path: "{{ directory }}"
        state: directory
        mode: '0775'

    - name: Ensure ssh directory is writable
      file:
        path: "{{ lookup('env','HOME') + '/.ssh' }}"
        state: directory
        mode: '0775'
        owner: awx
        group: root

    - name: Git checkout
      git:
        repo: "{{ url }}"
        dest: "{{ directory }}"
        accept_hostkey: true
        force: true
        key_file: "{{ gitlab_ssh_private_key_file }}"

    - name: Set engagement_data var
      set_fact:
        engagement_data: "{{ lookup('file', (directory + 'engagement.json')|join('/')) | from_json }}"

    - name: Print engagement data
      debug:
        var: engagement_data
        
