---
- name: Test Git Checkout
  hosts: all

  tasks:
    - name: Set fact
      set_fact:
        url: "{{ tower_webhook_payload.project.git_ssh_url }}"
        directory: "{{ playbook_dir }}/{{ tower_webhook_payload.project.id }}"

    - name: Create gitlab project directory
      file:
        path: "{{ directory }}"
        state: directory
        mode: '0775'

    - name: Git clone engagement repository
      git:
        repo: "{{ url }}"
        dest: "{{ directory }}"
        ssh_opts: "-o StrictHostKeyChecking=no"
        force: true
        key_file: /var/lib/awx/.ssh/bridge-private-key

    - name: Set engagement_data var
      set_fact:
        engagement_data: "{{ lookup('file', directory + 'engagement.json') | join ('/') | from_json }}"

    - name: Print engagement data
      debug:
        var: engagement_data
        
