---
- hosts: localhost
  gather_facts: false
  connection: local
  name: Git clone engagement repo

  tasks:
    - name: Set fact
      set_fact:
        url: "{{ tower_webhook_payload.project.git_ssh_url }}"
        directory: "/tmp/git_projects/{{ tower_webhook_payload.project.id }}"

    - name: Configure Git username and email
      shell: |
        git config --global user.email bot@bot.com;
        git config --global user.name bot

    - name: Cleanup existing working project directory
      file:
        path: "{{ directory }}"
        state: absent

    - name: Git clone
      shell: "git clone {{ url }} {{ directory }}"

    - name: Set engagement_data var
      set_fact:
        engagement_data: "{{ lookup('file', directory + '/engagement.json') | from_json }}"
        cacheable: true

    - name: File creation test
      file:
        path: "{{ directory }}/create_file_test.txt"
        state: touch
        mode: '0664'

    - name: Git add
      shell: git add .
      args:
        chdir: "{{ directory }}"

    - name: Git commit
      shell: |
        git commit -m 'Created by Ansible Tower bot'
      args:
        chdir: "{{ directory }}"
      register: git_commit
      changed_when:
        - git_commit.rc == 0
      failed_when:
        - git_commit.rc > 1

    - name: Git push
      shell: git push origin master
      args:
        chdir: "{{ directory }}"
      when:
        git_commit.rc == 0
